// Mocks generated by Mockito 5.4.2 from annotations
// in faro_clean_tdd/test/features/filters/domain/usecases/set_filter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:faro_clean_tdd/features/filters/domain/entities/filter.dart'
    as _i2;
import 'package:faro_clean_tdd/features/filters/domain/repositories/filter_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFilter_0 extends _i1.SmartFake implements _i2.Filter {
  _FakeFilter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FilterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterRepository extends _i1.Mock implements _i3.FilterRepository {
  MockFilterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Filter> setFilter(Map<_i2.FilterCategory, dynamic>? filters) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilter,
          [filters],
        ),
        returnValue: _i4.Future<_i2.Filter>.value(_FakeFilter_0(
          this,
          Invocation.method(
            #setFilter,
            [filters],
          ),
        )),
      ) as _i4.Future<_i2.Filter>);
}
