// Mocks generated by Mockito 5.4.2 from annotations
// in faro_clean_tdd/test/features/address/data/repositories/address_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:faro_clean_tdd/features/address/data/datasources/address_remote_data_source.dart'
    as _i2;
import 'package:faro_clean_tdd/features/address/data/models/address_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddressRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRemoteDataSource extends _i1.Mock
    implements _i2.AddressRemoteDataSource {
  MockAddressRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.AddressModel?> fetchAddressDataFromMap(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAddressDataFromMap,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i3.Future<_i4.AddressModel?>.value(),
      ) as _i3.Future<_i4.AddressModel?>);
  @override
  _i3.Future<_i4.AddressModel?> fetchAddressDataFromCurrentLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAddressDataFromCurrentLocation,
          [],
        ),
        returnValue: _i3.Future<_i4.AddressModel?>.value(),
      ) as _i3.Future<_i4.AddressModel?>);
}
