// Mocks generated by Mockito 5.4.4 from annotations
// in faro_clean_tdd/test/features/pick_image/data/repositories/picked_image_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i3;

// Package imports:
import 'package:mockito/mockito.dart' as _i1;

import 'package:faro_faro/features/pick_image/data/datasources/picked_image_local_data_source.dart'
    as _i2;
import 'package:faro_faro/features/pick_image/data/models/picked_image_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PickedImageLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPickedImageLocalDataSource extends _i1.Mock
    implements _i2.PickedImageLocalDataSource {
  MockPickedImageLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PickedImageModel?> pickImageFromGallery() =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImageFromGallery,
          [],
        ),
        returnValue: _i3.Future<_i4.PickedImageModel?>.value(),
      ) as _i3.Future<_i4.PickedImageModel?>);
}
